name: rstcheck

# Run this workflow for commits to doc files
on:
  push:
    paths:
      - ".github/workflows/rstcheck.yml"
      - "README.rst"
      - "docs/**"
      - "ci/rstcheck/*"
  pull_request:
    paths:
      - ".github/workflows/rstcheck.yml"
      - "README.rst"
      - "docs/**"
      - "ci/rstcheck/*"

jobs:
  rstcheck:
    name: rstcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install -r ci/rstcheck/requirements.txt

      - name: Run rstcheck
        run: |
          rstcheck -r --ignore-directives automodule --ignore-substitutions version,release,today .
