name: rstcheck

# Run this workflow for commits to doc files
on:
  push:
    paths:
      - ".github/workflows/rstcheck.yml"
      - "README.rst"
      - "docs/**"
  pull_request:
    paths:
      - ".github/workflows/rstcheck.yml"
      - "README.rst"
      - "docs/**"

jobs:
  rstcheck:
    name: rstcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install rstcheck[sphinx]==4.1.0

      - name: Run rstcheck
        run: |
          rstcheck -r --ignore-directives automodule --ignore-substitutions version,release,today .
